aspnet-core/aspnet-core/src/Framework.Web.Mvc/Models/Stripe/StripePurchaseViewModel.cs
using Framework.MultiTenancy.Payments.Stripe;

namespace Framework.Web.Models.Stripe
{
    public class StripePurchaseViewModel
    {
        public long PaymentId { get; set; }

        public string Description { get; set; }

        public decimal Amount { get; set; }

        public bool IsRecurring { get; set; }

        public bool UpdateSubscription { get; set; }

        public StripePaymentGatewayConfiguration Configuration { get; set; }
    }
}

aspnet-core/aspnet-core/src/Framework.Web.Mvc/Controllers/StripeController.cs
using System;
using System.Threading.Tasks;
using Abp.Domain.Uow;
using Microsoft.AspNetCore.Mvc;
using Framework.MultiTenancy.Payments;
using Framework.MultiTenancy.Payments.Stripe;
using Framework.MultiTenancy.Payments.Stripe.Dto;
using Framework.Web.Models.Stripe;

namespace Framework.Web.Controllers
{
    public class StripeController : StripeControllerBase
    {
        private readonly StripePaymentGatewayConfiguration _stripeConfiguration;
        private readonly IStripePaymentAppService _stripePaymentAppService;
        private readonly IPaymentAppService _paymentAppService;

        public StripeController(
            StripeGatewayManager stripeGatewayManager,
            StripePaymentGatewayConfiguration stripeConfiguration,
            IStripePaymentAppService stripePaymentAppService,
            IPaymentAppService paymentAppService)
            : base(stripeGatewayManager, stripeConfiguration)
        {
            _stripeConfiguration = stripeConfiguration;
            _stripePaymentAppService = stripePaymentAppService;
            _paymentAppService = paymentAppService;
        }

        public async Task<ActionResult> Purchase(long paymentId, bool isUpgrade = false)
        {
            var payment = await _paymentAppService.GetPaymentAsync(paymentId);
            if (payment.Status != SubscriptionPaymentStatus.NotPaid)
            {
                throw new ApplicationException("This payment is processed before");
            }

            var model = new StripePurchaseViewModel
            {
                PaymentId = payment.Id,
                Amount = payment.Amount,
                Description = payment.Description,
                IsRecurring = payment.IsRecurring,
                Configuration = _stripeConfiguration,
                UpdateSubscription = isUpgrade
            };

            if (payment.IsRecurring)
            {
                if (isUpgrade)
                {
                    return View("UpdateSubscription", model);
                }

                return View("Subscribe", model);
            }

            return View(model);
        }

        [HttpPost]
        [UnitOfWork(IsDisabled = true)]
        public async Task<ActionResult> ConfirmPayment(long paymentId, string stripeToken)
        {
            try
            {
                await _stripePaymentAppService.ConfirmPayment(
                    new StripeConfirmPaymentInput
                    {
                        PaymentId = paymentId,
                        StripeToken = stripeToken
                    });

                return Redirect(await GetSuccessUrlAsync(paymentId));
            }
            catch (Exception exception)
            {
                Logger.Error(exception.Message, exception);

                return Redirect(await GetErrorUrlAsync(paymentId));
            }
        }

        [HttpPost]
        [UnitOfWork(IsDisabled = true)]
        public async Task<ActionResult> CreateSubscription(long paymentId, string stripeToken)
        {
            try
            {
                await _stripePaymentAppService.CreateSubscription(new StripeCreateSubscriptionInput
                {
                    PaymentId = paymentId,
                    StripeToken = stripeToken
                });

                var returnUrl = await GetSuccessUrlAsync(paymentId);
                return Redirect(returnUrl);
            }
            catch (Exception exception)
            {
                Logger.Error(exception.Message, exception);

                var returnUrl = await GetErrorUrlAsync(paymentId);
                return Redirect(returnUrl);
            }
        }

        [HttpPost]
        [UnitOfWork(IsDisabled = true)]
        public virtual async Task<IActionResult> UpdateSubscription(long paymentId)
        {
            try
            {
                await _stripePaymentAppService.UpdateSubscription(
                    new StripeUpdateSubscriptionInput
                    {
                        PaymentId = paymentId
                    });

                var returnUrl = await GetSuccessUrlAsync(paymentId);
                return Redirect(returnUrl);
            }
            catch (Exception exception)
            {
                Logger.Error(exception.Message, exception);

                var returnUrl = await GetErrorUrlAsync(paymentId);
                return Redirect(returnUrl);
            }
        }

        private async Task<string> GetSuccessUrlAsync(long paymentId)
        {
            var payment = await _paymentAppService.GetPaymentAsync(paymentId);
            return payment.SuccessUrl + (payment.SuccessUrl.Contains("?") ? "&" : "?") + "paymentId=" + paymentId;
        }

        private async Task<string> GetErrorUrlAsync(long paymentId)
        {
            var payment = await _paymentAppService.GetPaymentAsync(paymentId);
            return payment.ErrorUrl + (payment.ErrorUrl.Contains("?") ? "&" : "?") + "paymentId=" + paymentId;
        }
    }
}

aspnet-core/aspnet-core/src/Framework.Web.Mvc/Views/Stripe/Purchase.cshtml
@using System.Globalization
@using Framework
@using Framework.Localization
@using Framework.Web.Resources
@model Framework.Web.Models.Stripe.StripePurchaseViewModel
@inject IWebResourceManager WebResourceManager
@{
    Layout = "~/Views/Account/_Layout.cshtml";
    ViewBag.DisableTenantChange = true;
}

@section Scripts
    {
    <script src="https://checkout.stripe.com/checkout.js" asp-append-version="true"></script>
    <script abp-src="/view-resources/Views/Stripe/_Purchase.js" asp-append-version="true"></script>
}

@section Styles{
    <link href="/metronic/common/css/login-1@(CultureHelper.IsRtl ? ".rtl":"").css" rel="stylesheet" />
}

<div class="kt-login__form">
    <div class="kt-login__title">
        <h3 class="m-0">@L("Purchase")</h3>
    </div>
    <hr class="border-green" />
    <div class="form-actions">
        <div class="form-group row">
            <label class="col-sm-4 control-label">@L("Item")</label>
            <div class="col-sm-8 text-right">
                <p class="form-control-static text-bold">
                    @Model.Description
                </p>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-4 control-label">@L("Price")</label>
            <div class="col-sm-8 text-right">
                <p class="form-control-static text-bold" id="totalPrice">
                    @FrameworkConsts.CurrencySign@(Model.Amount.ToString("N2"))
                </p>
            </div>
        </div>
    </div>

    <form id="stripeCheckoutForm" method="post" asp-action="ConfirmPayment" asp-controller="Stripe" class="register-form">
        <input type="hidden" name="stripeToken" value="" />
        <input type="hidden" name="amount" value="@Model.Amount.ToString("F", new CultureInfo("en-US", false))" />
        <input type="hidden" name="paymentId" value="@Model.PaymentId" />
        <input type="hidden" name="currency" value="@FrameworkConsts.Currency" />

        <input type="hidden" id="stripePublishableKey" value="@Model.Configuration.PublishableKey" />
        <button id="stripe-checkout" class="stripe-checkout-button btn btn-primary btn-block">@L("Purchase")</button>
    </form>
</div>

aspnet-core/aspnet-core/src/Framework.Web.Mvc/Views/Stripe/Subscribe.cshtml
@using System.Globalization
@using Framework
@using Framework.Localization
@using Framework.Web.Resources
@model Framework.Web.Models.Stripe.StripePurchaseViewModel
@inject IWebResourceManager WebResourceManager
@{
    Layout = "~/Views/Account/_Layout.cshtml";
    ViewBag.DisableTenantChange = true;
}

@section Scripts
    {
    <script src="https://checkout.stripe.com/checkout.js" asp-append-version="true"></script>
    <script abp-src="/view-resources/Views/Stripe/_Subscribe.js" asp-append-version="true"></script>
}

@section Styles{
    <link href="/metronic/common/css/login-1@(CultureHelper.IsRtl ? ".rtl":"").css" rel="stylesheet" />
}

<div class="kt-login__form">
    <div class="kt-login__title">
        <h3 class="m-0">@L("Purchase")</h3>
    </div>
    <hr class="border-green" />
    <div class="form-actions">
        <div class="form-group row">
            <label class="col-sm-4 control-label">@L("Item")</label>
            <div class="col-sm-8 text-right">
                <p class="form-control-static text-bold">
                    @Model.Description
                </p>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-4 control-label">@L("Price")</label>
            <div class="col-sm-8 text-right">
                <p class="form-control-static text-bold" id="totalPrice">
                    @FrameworkConsts.CurrencySign@(Model.Amount.ToString("N2"))
                </p>
            </div>
        </div>
    </div>

    <form id="stripeCheckoutForm" method="post" asp-action="CreateSubscription" asp-controller="Stripe" class="register-form">
        <input type="hidden" name="stripeToken" value="" />
        <input type="hidden" name="amount" value="@Model.Amount.ToString("F",  new CultureInfo("en-US", false))" />
        <input type="hidden" name="paymentId" value="@Model.PaymentId" />
        <input type="hidden" name="currency" value="@FrameworkConsts.Currency" />

        <input type="hidden" id="stripePublishableKey" value="@Model.Configuration.PublishableKey" />
        <button id="stripe-checkout" class="stripe-checkout-button btn btn-primary btn-block">@L("Purchase")</button>
    </form>
</div>

aspnet-core/aspnet-core/src/Framework.Web.Mvc/Views/Stripe/UpdateSubscription.cshtml
@using Framework.Localization
@model Framework.Web.Models.Stripe.StripePurchaseViewModel
@{
    Layout = "~/Views/Account/_Layout.cshtml";
    ViewBag.DisableTenantChange = true;
}

@section Styles{
    <link href="/metronic/common/css/login-1@(CultureHelper.IsRtl ? ".rtl":"").css" rel="stylesheet" />
}

<div class="kt-login__form">
    <div class="kt-login__title">
        <h3 class="m-0">@L("Purchase")</h3>
    </div>
    <hr class="border-green" />
    <div class="form-actions">
        <div class="form-group row">
            <label class="col-sm-4 control-label">@L("Item")</label>
            <div class="col-sm-8 text-right">
                <p class="form-control-static text-bold">
                    @Model.Description
                </p>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-12 control-label">@L("RecurringSubscriptionUpgradeNote")</label>
        </div>
    </div>

    <form id="stripeCheckoutForm" method="post" asp-action="UpdateSubscription" asp-controller="Stripe" class="register-form">
        <input type="hidden" name="paymentId" value="@Model.PaymentId" />

        <button type="submit" class="stripe-checkout-button btn btn-primary btn-block">@L("Upgrade")</button>
    </form>
</div>